# Generated by Django 5.2.8 on 2025-11-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(choices=[('dhaka', 'Dhaka'), ('mymensingh', 'Mymensingh'), ('khulna', 'Khulna'), ('chatragram', 'Chatragram'), ('rajshahi', 'Rajshahi')], max_length=11)),
                ('payment', models.CharField(choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('rocket', 'Rocket')], max_length=21)),
            ],
        ),
    ]
