# Generated by Django 5.2.8 on 2025-11-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_customersinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersinfo',
            name='age',
            field=models.IntegerField(default=14),
        ),
    ]
